#!/bin/bash

# pylint's error code is composed of a sum of (binary numbers):
# 0=ok, 1=fatal so even numbers are mainly just warnings
# (so do not fail tests on warnings)

pylint "$@"
retval=$?

if $(( retval % 2 )); then
	exit 1
else
	exit 0
fi
